name: PostgreSQL Installcheck

on:
  pull_request:
    branches:
      - main

jobs:
  installcheck:
    name: Test ${{ matrix.pg }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pg: [16, 17, 18]
    container: 
      image: pgxn/pgxn-tools
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: apt-get update && apt-get install -y curl libcurl4-openssl-dev liblz4-dev libzstd-dev libkrb5-dev autoconf automake libtool
      # https://github.com/pgxn/docker-pgxn-tools?tab=readme-ov-file#unprivileged-user-workflow
      - run: pg-start ${{ matrix.pg }}
      - run: chown -R postgres:postgres .
      - run: make install-dependencies
      - run: gosu postgres pg-build-test
      - name: Display results
        if: failure()
        run: |
          cat regression.diffs
          cat /__w/pg_timeseries/pg_timeseries/log/initdb.log
